/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import proyecto1so.Company;
import proyecto1so.SimulationController;
import proyecto1so.UtilityGraph;

/**
 *
 * @author berna
 */
public class DashboardMenu extends javax.swing.JFrame {

    
    private final Company apple;
    private final Company hp;
    private final Company dell;
    private int[] workerTimes = {4000, 4000, 1000, 200, 2000 };
    private final SimulationController controller;
    

    /**
     * Creates new form DashboardMenu
     */
    public DashboardMenu(SimulationController controller, Company apple, Company hp, Company dell) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = controller;
        this.apple = apple;
        this.hp = apple;
        this.dell = apple;
        
        JLabel[] appleManagerLabels= {jLabelApplePmStatus, jLabelDaysToDeliver}; 
        JLabel[] appleDirectorLabels= {jLabelAppleDirStatus, jLabelAppleGanancia, jLabelAppleCost, jLabelAppleUtility}; 
        apple.getProjectManager().setManagerLabels(appleManagerLabels);
        apple.getDirector().setDirectorJlabels(appleDirectorLabels);
        apple.getProjectManager().updateLabels();
        apple.getDirector().updateDirectorJLabels();
        
        JLabel[] hpManagerLabels= {jLabelDellPmStatus1, jLabelDaysToDeliver}; 
        JLabel[] hpDirectorLabels= {jLabelDellDirStatus1, jLabelDellGanancia1, jLabelDellCost1, jLabelDellUtility1}; 
        hp.getProjectManager().setManagerLabels(hpManagerLabels);
        hp.getDirector().setDirectorJlabels(hpDirectorLabels);
        hp.getProjectManager().updateLabels();
        hp.getDirector().updateDirectorJLabels();
        
        JLabel[] dellManagerLabels= {jLabelHPPmStatus2, jLabelDaysToDeliver}; 
        JLabel[] dellDirectorLabels= {jLabelHPDirStatus2, jLabelHPGanancia2, jLabelHPCost2, jLabelHPUtility2}; 
        dell.getProjectManager().setManagerLabels(dellManagerLabels);
        dell.getDirector().setDirectorJlabels(dellDirectorLabels);
        
        int count = apple.countWorkers("Motherboard");
        jLabelApplePlacasCant.setText(Integer.toString(count));
        
        count = apple.countWorkers("CPU");
        jLabelAppleCpuCant.setText(Integer.toString(count));
        
        count = apple.countWorkers("RAM");
        jLabelAppleRamCant.setText(Integer.toString(count));
        
        count = apple.countWorkers("PowerSupply");
        jLabelApplePsuCant.setText(Integer.toString(count));
        
        count = apple.countWorkers("GraphicCard");
        jLabelAppleGpuCant.setText(Integer.toString(count));
        
        jLabelAppleAssCant.setText(Integer.toString(apple.getAssemblerCount()));
        
        count = hp.countWorkers("Motherboard");
        jLabelDellPlacasCant1.setText(Integer.toString(count));
        
        count = hp.countWorkers("CPU");
        jLabelDellCpuCant1.setText(Integer.toString(count));
        
        count = hp.countWorkers("RAM");
        jLabelDellRamCant1.setText(Integer.toString(count));
        
        count = hp.countWorkers("PowerSupply");
        jLabelDellPsuCant1.setText(Integer.toString(count));
        
        count = hp.countWorkers("GraphicCard");
        jLabelDellGpuCant1.setText(Integer.toString(count));
        
        jLabelDellAssCant1.setText(Integer.toString(hp.getAssemblerCount()));
        
        count = dell.countWorkers("Motherboard");
        jLabelHPPlacasCant2.setText(Integer.toString(count));
        
        count = dell.countWorkers("CPU");
        jLabelHPCpuCant2.setText(Integer.toString(count));
        
        count = dell.countWorkers("RAM");
        jLabelHPRamCant2.setText(Integer.toString(count));
        
        count = dell.countWorkers("PowerSupply");
        jLabelHPPsuCant2.setText(Integer.toString(count));
        
        count = dell.countWorkers("GraphicCard");
        jLabelHPGpuCant2.setText(Integer.toString(count));
        
        jLabelHPAssCant2.setText(Integer.toString(dell.getAssemblerCount()));
        dell.getProjectManager().updateLabels();
        dell.getDirector().updateDirectorJLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApplePlacaM = new javax.swing.JButton();
        jButtonApplePlacaP = new javax.swing.JButton();
        jLabelApplePlacasCant = new javax.swing.JLabel();
        jButtonAppleCpuM = new javax.swing.JButton();
        jLabelAppleCpuCant = new javax.swing.JLabel();
        jButtonAppleCpuP = new javax.swing.JButton();
        jButtonAppleRamM = new javax.swing.JButton();
        jLabelAppleRamCant = new javax.swing.JLabel();
        jButtonAppleRamP = new javax.swing.JButton();
        jButtonApplePsuM = new javax.swing.JButton();
        jLabelApplePsuCant = new javax.swing.JLabel();
        jButtonApplePsuP = new javax.swing.JButton();
        jButtonAppleGpuM = new javax.swing.JButton();
        jLabelAppleGpuCant = new javax.swing.JLabel();
        jButtonAppleGpuP = new javax.swing.JButton();
        jButtonAppleAssM = new javax.swing.JButton();
        jLabelAppleAssCant = new javax.swing.JLabel();
        jButtonAppleAssP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelApplePmStatus = new javax.swing.JLabel();
        jLabelAppleDirStatus = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelApplePcGpu = new javax.swing.JLabel();
        jLabelApplePc = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelAppleUtility = new javax.swing.JLabel();
        jLabelAppleCost = new javax.swing.JLabel();
        jLabelAppleGanancia = new javax.swing.JLabel();
        jLabel22APPLE = new javax.swing.JLabel();
        jLabel23APPLE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonStartSim = new javax.swing.JButton();
        jButtonStopSim = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDaysToDeliver = new javax.swing.JLabel();
        jLabelSimDaysPassed = new javax.swing.JLabel();
        jButtonShowGraph = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabelDellPcGpu1 = new javax.swing.JLabel();
        jLabelDellPc1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelDellUtility1 = new javax.swing.JLabel();
        jLabelDellCost1 = new javax.swing.JLabel();
        jLabelDellGanancia1 = new javax.swing.JLabel();
        jButtonDellPlacaM1 = new javax.swing.JButton();
        jButtonApplePlacaP1 = new javax.swing.JButton();
        jLabelDellPlacasCant1 = new javax.swing.JLabel();
        jButtonDellCpuM1 = new javax.swing.JButton();
        jLabelDellCpuCant1 = new javax.swing.JLabel();
        jButtonDellCpuP1 = new javax.swing.JButton();
        jButtonDellRamM1 = new javax.swing.JButton();
        jLabelDellRamCant1 = new javax.swing.JLabel();
        jButtonDellRamP1 = new javax.swing.JButton();
        jButtonDellPsuM1 = new javax.swing.JButton();
        jLabelDellPsuCant1 = new javax.swing.JLabel();
        jButtonDellPsuP1 = new javax.swing.JButton();
        jButtonDellGpuM1 = new javax.swing.JButton();
        jLabelDellGpuCant1 = new javax.swing.JLabel();
        jButtonDellGpuP1 = new javax.swing.JButton();
        jButtonDellAssM1 = new javax.swing.JButton();
        jLabelDellAssCant1 = new javax.swing.JLabel();
        jButtonDellAssP1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26DELL = new javax.swing.JLabel();
        jLabel27DELL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelDellPmStatus1 = new javax.swing.JLabel();
        jLabelDellDirStatus1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabelHPPcGpu2 = new javax.swing.JLabel();
        jLabelHPPc2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabelHPUtility2 = new javax.swing.JLabel();
        jLabelHPCost2 = new javax.swing.JLabel();
        jLabelHPGanancia2 = new javax.swing.JLabel();
        jButtonHPPlacaM2 = new javax.swing.JButton();
        jButtonHPPlacaP2 = new javax.swing.JButton();
        jLabelHPPlacasCant2 = new javax.swing.JLabel();
        jButtonHPCpuM2 = new javax.swing.JButton();
        jLabelHPCpuCant2 = new javax.swing.JLabel();
        jButtonHPCpuP2 = new javax.swing.JButton();
        jButtonHPRamM2 = new javax.swing.JButton();
        jLabelHPRamCant2 = new javax.swing.JLabel();
        jButtonHPRamP2 = new javax.swing.JButton();
        jButtonHPPsuM2 = new javax.swing.JButton();
        jLabelHPPsuCant2 = new javax.swing.JLabel();
        jButtonHPPsuP2 = new javax.swing.JButton();
        jButtonHPGpuM2 = new javax.swing.JButton();
        jLabelHPGpuCant2 = new javax.swing.JLabel();
        jButtonHPGpuP2 = new javax.swing.JButton();
        jButtonHPAssM2 = new javax.swing.JButton();
        jLabelHPAssCant2 = new javax.swing.JLabel();
        jButtonHPAssP2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43HP = new javax.swing.JLabel();
        jLabel44HP = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabelHPPmStatus2 = new javax.swing.JLabel();
        jLabelHPDirStatus2 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButtonCSV = new javax.swing.JButton();
        jButtonGoToSTORAGE = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonApplePlacaM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePlacaM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePlacaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonApplePlacaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePlacaMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePlacaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 20, 20));

        jButtonApplePlacaP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePlacaP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePlacaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonApplePlacaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePlacaPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePlacaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 20, 20));

        jLabelApplePlacasCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePlacasCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePlacasCant.setText("x");
        getContentPane().add(jLabelApplePlacasCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jButtonAppleCpuM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleCpuM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleCpuM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleCpuM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleCpuMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleCpuM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 20, 20));

        jLabelAppleCpuCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleCpuCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleCpuCant.setText("x");
        getContentPane().add(jLabelAppleCpuCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jButtonAppleCpuP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleCpuP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleCpuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleCpuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleCpuPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleCpuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 20, 20));

        jButtonAppleRamM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleRamM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleRamM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleRamM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleRamMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleRamM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 20, 20));

        jLabelAppleRamCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleRamCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleRamCant.setText("x");
        getContentPane().add(jLabelAppleRamCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jButtonAppleRamP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleRamP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleRamP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleRamP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleRamPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleRamP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 20, 20));

        jButtonApplePsuM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePsuM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePsuM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonApplePsuM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePsuMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePsuM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 20, 20));

        jLabelApplePsuCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePsuCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePsuCant.setText("x");
        getContentPane().add(jLabelApplePsuCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jButtonApplePsuP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePsuP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePsuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonApplePsuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePsuPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePsuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 20, 20));

        jButtonAppleGpuM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleGpuM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleGpuM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleGpuM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleGpuMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleGpuM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 20, 20));

        jLabelAppleGpuCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleGpuCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleGpuCant.setText("x");
        getContentPane().add(jLabelAppleGpuCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jButtonAppleGpuP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleGpuP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleGpuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleGpuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleGpuPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleGpuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 20, 20));

        jButtonAppleAssM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleAssM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleAssM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleAssM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleAssMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleAssM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 20, 20));

        jLabelAppleAssCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleAssCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleAssCant.setText("x");
        getContentPane().add(jLabelAppleAssCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jButtonAppleAssP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleAssP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleAssP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleAssP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleAssPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleAssP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 20, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Placas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 37, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CPU");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 37, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("RAM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 37, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("GPU");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 37, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PSU");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 37, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Assembler");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("P.M Status:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Dir. Status:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabelApplePmStatus.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePmStatus.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePmStatus.setText("Webeando");
        getContentPane().add(jLabelApplePmStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabelAppleDirStatus.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleDirStatus.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleDirStatus.setText("Webeando");
        getContentPane().add(jLabelAppleDirStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Ganancia en Bruto:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Costos Operativos:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Utilidad total:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabelApplePcGpu.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePcGpu.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePcGpu.setText("GPU:");
        getContentPane().add(jLabelApplePcGpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabelApplePc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePc.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePc.setText("DEF:");
        getContentPane().add(jLabelApplePc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("PC Listas:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 57, -1));

        jLabelAppleUtility.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleUtility.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleUtility.setText("xxK");
        getContentPane().add(jLabelAppleUtility, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 43, -1));

        jLabelAppleCost.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleCost.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleCost.setText("xxK");
        getContentPane().add(jLabelAppleCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 43, -1));

        jLabelAppleGanancia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleGanancia.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleGanancia.setText("xxK");
        getContentPane().add(jLabelAppleGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 43, -1));

        jLabel22APPLE.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22APPLE.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22APPLE.setText("x");
        getContentPane().add(jLabel22APPLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel23APPLE.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23APPLE.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23APPLE.setText("x");
        getContentPane().add(jLabel23APPLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Trabajadores:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VS.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, 80));

        jButtonStartSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/START.png"))); // NOI18N
        jButtonStartSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartSimActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStartSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 80, 40));

        jButtonStopSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/STOP.png"))); // NOI18N
        jButtonStopSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopSimActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStopSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 21, 80, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dias totales simulados:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dias para Entrega:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabelDaysToDeliver.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDaysToDeliver.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDaysToDeliver.setText("XX");
        getContentPane().add(jLabelDaysToDeliver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 37, -1));

        jLabelSimDaysPassed.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelSimDaysPassed.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSimDaysPassed.setText("xxxx");
        getContentPane().add(jLabelSimDaysPassed, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 37, -1));

        jButtonShowGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GRAFO.png"))); // NOI18N
        jButtonShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowGraphActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 80, 40));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Utilidad total:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabelDellPcGpu1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPcGpu1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPcGpu1.setText("GPU:");
        getContentPane().add(jLabelDellPcGpu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jLabelDellPc1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPc1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPc1.setText("DEF:");
        getContentPane().add(jLabelDellPc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("PC Listas:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 57, -1));

        jLabelDellUtility1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellUtility1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellUtility1.setText("xxK");
        getContentPane().add(jLabelDellUtility1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 43, -1));

        jLabelDellCost1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellCost1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellCost1.setText("xxK");
        getContentPane().add(jLabelDellCost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 43, -1));

        jLabelDellGanancia1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellGanancia1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellGanancia1.setText("xxK");
        getContentPane().add(jLabelDellGanancia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 43, -1));

        jButtonDellPlacaM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellPlacaM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellPlacaM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellPlacaM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellPlacaM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellPlacaM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 20, 20));

        jButtonApplePlacaP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePlacaP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePlacaP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonApplePlacaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePlacaP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePlacaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 20, 20));

        jLabelDellPlacasCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPlacasCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPlacasCant1.setText("x");
        getContentPane().add(jLabelDellPlacasCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jButtonDellCpuM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellCpuM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellCpuM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellCpuM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellCpuM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellCpuM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 20, 20));

        jLabelDellCpuCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellCpuCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellCpuCant1.setText("x");
        getContentPane().add(jLabelDellCpuCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButtonDellCpuP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellCpuP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellCpuP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellCpuP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellCpuP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellCpuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 20, 20));

        jButtonDellRamM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellRamM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellRamM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellRamM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellRamM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellRamM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 20, 20));

        jLabelDellRamCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellRamCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellRamCant1.setText("x");
        getContentPane().add(jLabelDellRamCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jButtonDellRamP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellRamP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellRamP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellRamP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellRamP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellRamP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 20, 20));

        jButtonDellPsuM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellPsuM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellPsuM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellPsuM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellPsuM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellPsuM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 20, 20));

        jLabelDellPsuCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPsuCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPsuCant1.setText("x");
        getContentPane().add(jLabelDellPsuCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jButtonDellPsuP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellPsuP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellPsuP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellPsuP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellPsuP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellPsuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 20, 20));

        jButtonDellGpuM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellGpuM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellGpuM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellGpuM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellGpuM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellGpuM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 20, 20));

        jLabelDellGpuCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellGpuCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellGpuCant1.setText("x");
        getContentPane().add(jLabelDellGpuCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        jButtonDellGpuP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellGpuP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellGpuP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellGpuP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellGpuP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellGpuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 20, 20));

        jButtonDellAssM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellAssM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellAssM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellAssM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellAssM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellAssM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 20, 20));

        jLabelDellAssCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellAssCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellAssCant1.setText("x");
        getContentPane().add(jLabelDellAssCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jButtonDellAssP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellAssP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellAssP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellAssP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellAssP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellAssP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 20, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Placas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 37, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("CPU");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 37, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("RAM");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 37, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("GPU");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 37, -1));

        jLabel26DELL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel26DELL.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26DELL.setText("x");
        getContentPane().add(jLabel26DELL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jLabel27DELL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel27DELL.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27DELL.setText("x");
        getContentPane().add(jLabel27DELL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Trabajadores:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("PSU");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 37, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Assembler");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("P.M Status:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Dir. Status:");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jLabelDellPmStatus1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPmStatus1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPmStatus1.setText("Webeando");
        getContentPane().add(jLabelDellPmStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabelDellDirStatus1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellDirStatus1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellDirStatus1.setText("Webeando");
        getContentPane().add(jLabelDellDirStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Ganancia en Bruto:");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Costos Operativos:");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Utilidad total:");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        jLabelHPPcGpu2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPcGpu2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPcGpu2.setText("GPU:");
        getContentPane().add(jLabelHPPcGpu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jLabelHPPc2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPc2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPc2.setText("DEF:");
        getContentPane().add(jLabelHPPc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("PC Listas:");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 57, -1));

        jLabelHPUtility2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPUtility2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPUtility2.setText("xxK");
        getContentPane().add(jLabelHPUtility2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 43, -1));

        jLabelHPCost2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPCost2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPCost2.setText("xxK");
        getContentPane().add(jLabelHPCost2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 43, -1));

        jLabelHPGanancia2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPGanancia2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPGanancia2.setText("xxK");
        getContentPane().add(jLabelHPGanancia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 43, -1));

        jButtonHPPlacaM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPlacaM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPlacaM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPPlacaM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPlacaM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPlacaM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 20, 20));

        jButtonHPPlacaP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPlacaP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPlacaP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPPlacaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPlacaP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPlacaP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 20, 20));

        jLabelHPPlacasCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPlacasCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPlacasCant2.setText("x");
        getContentPane().add(jLabelHPPlacasCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jButtonHPCpuM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPCpuM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPCpuM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPCpuM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPCpuM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPCpuM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 20, 20));

        jLabelHPCpuCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPCpuCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPCpuCant2.setText("x");
        getContentPane().add(jLabelHPCpuCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jButtonHPCpuP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPCpuP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPCpuP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPCpuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPCpuP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPCpuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 20, 20));

        jButtonHPRamM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPRamM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPRamM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPRamM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPRamM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPRamM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 20, 20));

        jLabelHPRamCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPRamCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPRamCant2.setText("x");
        getContentPane().add(jLabelHPRamCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        jButtonHPRamP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPRamP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPRamP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPRamP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPRamP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPRamP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 20, 20));

        jButtonHPPsuM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPsuM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPsuM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPPsuM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPsuM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPsuM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 20, 20));

        jLabelHPPsuCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPsuCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPsuCant2.setText("x");
        getContentPane().add(jLabelHPPsuCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jButtonHPPsuP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPsuP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPsuP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPPsuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPsuP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPsuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 20, 20));

        jButtonHPGpuM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPGpuM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPGpuM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPGpuM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPGpuM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPGpuM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 20, 20));

        jLabelHPGpuCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPGpuCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPGpuCant2.setText("x");
        getContentPane().add(jLabelHPGpuCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jButtonHPGpuP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPGpuP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPGpuP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPGpuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPGpuP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPGpuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 20, 20));

        jButtonHPAssM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPAssM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPAssM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPAssM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPAssM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPAssM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 20, 20));

        jLabelHPAssCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPAssCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPAssCant2.setText("x");
        getContentPane().add(jLabelHPAssCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        jButtonHPAssP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPAssP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPAssP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPAssP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPAssP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPAssP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 20, 20));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Placas");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 37, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("CPU");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 37, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("RAM");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 37, -1));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("GPU");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 37, -1));

        jLabel43HP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel43HP.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43HP.setText("x");
        getContentPane().add(jLabel43HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jLabel44HP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel44HP.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44HP.setText("x");
        getContentPane().add(jLabel44HP, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Trabajadores:");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("PSU");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 37, -1));

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Assembler");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("P.M Status:");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Dir. Status:");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        jLabelHPPmStatus2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPmStatus2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPmStatus2.setText("Webeando");
        getContentPane().add(jLabelHPPmStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jLabelHPDirStatus2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPDirStatus2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPDirStatus2.setText("Webeando");
        getContentPane().add(jLabelHPDirStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Ganancia en Bruto:");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Costos Operativos:");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        jButtonCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CSV.png"))); // NOI18N
        getContentPane().add(jButtonCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 40));

        jButtonGoToSTORAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/STORAGE.png"))); // NOI18N
        jButtonGoToSTORAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoToSTORAGEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGoToSTORAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 80, 40));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 753, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApplePlacaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePlacaMActionPerformed
        // TODO add your handling code here:
        apple.selectWorker("Motherboard");
        int count = apple.countWorkers("Motherboard");
        jLabelApplePlacasCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonApplePlacaMActionPerformed

    private void jButtonApplePlacaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePlacaPActionPerformed
        // TODO add your handling code here:
        apple.addWorker("Motherboard", workerTimes[0]* controller.getDayDuration());
        int count = apple.countWorkers("Motherboard");
        jLabelApplePlacasCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonApplePlacaPActionPerformed

    private void jButtonAppleCpuMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleCpuMActionPerformed
        // TODO add your handling code here:
        apple.selectWorker("CPU");
        int count = apple.countWorkers("CPU");
        jLabelAppleCpuCant.setText(Integer.toString(count));

    }//GEN-LAST:event_jButtonAppleCpuMActionPerformed

    private void jButtonAppleCpuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleCpuPActionPerformed
        // TODO add your handling code here:
        apple.addWorker("CPU", workerTimes[1]* controller.getDayDuration());
        int count = apple.countWorkers("CPU");
        jLabelAppleCpuCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonAppleCpuPActionPerformed

    private void jButtonAppleRamMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleRamMActionPerformed
        // TODO add your handling code here:
        apple.selectWorker("RAM");
        int count = apple.countWorkers("RAM");
        jLabelAppleRamCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonAppleRamMActionPerformed

    private void jButtonAppleRamPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleRamPActionPerformed
        // TODO add your handling code here:
        apple.addWorker("RAM", workerTimes[2]* controller.getDayDuration());
        int count = apple.countWorkers("RAM");
        jLabelAppleRamCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonAppleRamPActionPerformed

    private void jButtonApplePsuMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePsuMActionPerformed
        // TODO add your handling code here:
        apple.selectWorker("PowerSupply");
        int count = apple.countWorkers("PowerSupply");
        jLabelApplePsuCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonApplePsuMActionPerformed

    private void jButtonApplePsuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePsuPActionPerformed
        // TODO add your handling code here:
        apple.addWorker("PowerSupply", workerTimes[3]* controller.getDayDuration());
        int count = apple.countWorkers("PowerSupply");
        jLabelApplePsuCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonApplePsuPActionPerformed

    private void jButtonAppleGpuMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleGpuMActionPerformed
        // TODO add your handling code here:
        apple.selectWorker("GraphicCard");
        int count = apple.countWorkers("GraphicCard");
        jLabelAppleGpuCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonAppleGpuMActionPerformed

    private void jButtonAppleGpuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleGpuPActionPerformed
        // TODO add your handling code here:
        apple.addWorker("GraphicCard", workerTimes[4]* controller.getDayDuration());
        int count = apple.countWorkers("GraphicCard");
        jLabelAppleGpuCant.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonAppleGpuPActionPerformed

    private void jButtonAppleAssMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleAssMActionPerformed
        // TODO add your handling code here:
        apple.selectAss();
        jLabelAppleAssCant.setText(Integer.toString(apple.getAssemblerCount()));
    }//GEN-LAST:event_jButtonAppleAssMActionPerformed

    private void jButtonAppleAssPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleAssPActionPerformed
        // TODO add your handling code here:
        apple.addAssembler(2 * controller.getDayDuration());
        jLabelAppleAssCant.setText(Integer.toString(apple.getAssemblerCount()));
    }//GEN-LAST:event_jButtonAppleAssPActionPerformed

    private void jButtonStartSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStartSimActionPerformed

    private void jButtonStopSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStopSimActionPerformed

    private void jButtonDellPlacaM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellPlacaM1ActionPerformed
        hp.selectWorker("Motherboard");
        int count = hp.countWorkers("Motherboard");
        jLabelDellPlacasCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellPlacaM1ActionPerformed

    private void jButtonApplePlacaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePlacaP1ActionPerformed
        hp.addWorker("Motherboard", workerTimes[0]* controller.getDayDuration());
        int count = hp.countWorkers("Motherboard");
        jLabelDellPlacasCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonApplePlacaP1ActionPerformed

    private void jButtonDellCpuM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellCpuM1ActionPerformed
        hp.selectWorker("CPU");
        int count = hp.countWorkers("CPU");
        jLabelDellCpuCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellCpuM1ActionPerformed

    private void jButtonDellCpuP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellCpuP1ActionPerformed
        hp.addWorker("CPU", workerTimes[1]* controller.getDayDuration());
        int count = hp.countWorkers("CPU");
        jLabelDellCpuCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellCpuP1ActionPerformed

    private void jButtonDellRamM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellRamM1ActionPerformed
        hp.selectWorker("RAM");
        int count = hp.countWorkers("RAM");
        jLabelDellRamCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellRamM1ActionPerformed

    private void jButtonDellRamP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellRamP1ActionPerformed
        hp.addWorker("RAM", workerTimes[2]* controller.getDayDuration());
        int count = hp.countWorkers("RAM");
        jLabelDellRamCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellRamP1ActionPerformed

    private void jButtonDellPsuM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellPsuM1ActionPerformed
        hp.selectWorker("PowerSupply");
        int count = hp.countWorkers("PowerSupply");
        jLabelDellPsuCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellPsuM1ActionPerformed

    private void jButtonDellPsuP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellPsuP1ActionPerformed
        hp.addWorker("PowerSupply", workerTimes[3]* controller.getDayDuration());
        int count = hp.countWorkers("PowerSupply");
        jLabelDellPsuCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellPsuP1ActionPerformed

    private void jButtonDellGpuM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellGpuM1ActionPerformed
        hp.selectWorker("GraphicCard");
        int count = hp.countWorkers("GraphicCard");
        jLabelDellGpuCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellGpuM1ActionPerformed

    private void jButtonDellGpuP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellGpuP1ActionPerformed
        hp.addWorker("GraphicCard", workerTimes[4]* controller.getDayDuration());
        int count = hp.countWorkers("GraphicCard");
        jLabelDellGpuCant1.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonDellGpuP1ActionPerformed

    private void jButtonDellAssM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellAssM1ActionPerformed
        // TODO add your handling code here:
        hp.selectAss();
        jLabelDellAssCant1.setText(Integer.toString(hp.getAssemblerCount()));
    }//GEN-LAST:event_jButtonDellAssM1ActionPerformed

    private void jButtonDellAssP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellAssP1ActionPerformed
        // TODO add your handling code here:
        hp.addAssembler(2 * controller.getDayDuration());
        jLabelDellAssCant1.setText(Integer.toString(hp.getAssemblerCount()));
    }//GEN-LAST:event_jButtonDellAssP1ActionPerformed

    private void jButtonHPPlacaM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPlacaM2ActionPerformed
        dell.selectWorker("Motherboard");
        int count = dell.countWorkers("Motherboard");
        jLabelHPPlacasCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPPlacaM2ActionPerformed

    private void jButtonHPPlacaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPlacaP2ActionPerformed
        dell.addWorker("Motherboard", workerTimes[0]* controller.getDayDuration());
        int count = dell.countWorkers("Motherboard");
        jLabelHPPlacasCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPPlacaP2ActionPerformed

    private void jButtonHPCpuM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPCpuM2ActionPerformed
        dell.selectWorker("CPU");
        int count = dell.countWorkers("CPU");
        jLabelHPCpuCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPCpuM2ActionPerformed

    private void jButtonHPCpuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPCpuP2ActionPerformed
        dell.addWorker("CPU", workerTimes[1]* controller.getDayDuration());
        int count = dell.countWorkers("CPU");
        jLabelHPCpuCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPCpuP2ActionPerformed

    private void jButtonHPRamM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPRamM2ActionPerformed
        dell.selectWorker("RAM");
        int count = dell.countWorkers("RAM");
        jLabelHPRamCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPRamM2ActionPerformed

    private void jButtonHPRamP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPRamP2ActionPerformed
        dell.addWorker("RAM", workerTimes[2]* controller.getDayDuration());
        int count = dell.countWorkers("RAM");
        jLabelHPRamCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPRamP2ActionPerformed

    private void jButtonHPPsuM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPsuM2ActionPerformed
        dell.selectWorker("PowerSupply");
        int count = dell.countWorkers("PowerSupply");
        jLabelHPPsuCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPPsuM2ActionPerformed

    private void jButtonHPPsuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPsuP2ActionPerformed
        dell.addWorker("PowerSupply", workerTimes[3]* controller.getDayDuration());
        int count = dell.countWorkers("PowerSupply");
        jLabelHPPsuCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPPsuP2ActionPerformed

    private void jButtonHPGpuM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPGpuM2ActionPerformed
        dell.selectWorker("GraphicCard");
        int count = dell.countWorkers("GraphicCard");
        jLabelHPGpuCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPGpuM2ActionPerformed

    private void jButtonHPGpuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPGpuP2ActionPerformed
        dell.addWorker("GraphicCard", workerTimes[4]* controller.getDayDuration());
        int count = dell.countWorkers("GraphicCard");
        jLabelHPGpuCant2.setText(Integer.toString(count));
    }//GEN-LAST:event_jButtonHPGpuP2ActionPerformed

    private void jButtonHPAssM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPAssM2ActionPerformed
        // TODO add your handling code here:
        dell.selectAss();
        jLabelHPAssCant2.setText(Integer.toString(hp.getAssemblerCount()));
    }//GEN-LAST:event_jButtonHPAssM2ActionPerformed

    private void jButtonHPAssP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPAssP2ActionPerformed
        // TODO add your handling code here:
        dell.addAssembler(2 * controller.getDayDuration());
        jLabelHPAssCant2.setText(Integer.toString(dell.getAssemblerCount()));
    }//GEN-LAST:event_jButtonHPAssP2ActionPerformed

    private void jButtonGoToSTORAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoToSTORAGEActionPerformed
        StorageGUI a = new StorageGUI(controller, apple, hp, dell);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGoToSTORAGEActionPerformed

    private void jButtonShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowGraphActionPerformed
        // TODO add your handling code here:
                UtilityGraph graph = new UtilityGraph("Ganancias de HP, Apple y Dell");
        graph.display();  // Mostrar la gráfica


        // Simulación de los días
        int simulationDays = 30;
        for (int day = 1; day <= simulationDays; day++) {
            // Obtener las ganancias de cada compañía
            double hpProfit = hp.getGrossIncome() - hp.getOperationalCosts();
            double appleProfit = apple.getGrossIncome() - apple.getOperationalCosts();
            double dellProfit = dell.getGrossIncome() - dell.getOperationalCosts();

            // Actualizar el gráfico
            graph.updateGraph(day, hpProfit, appleProfit, dellProfit);

                    try {
                        // Simular un día de espera
                        Thread.sleep(controller.getDayDuration() * 1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DashboardMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }}
    }//GEN-LAST:event_jButtonShowGraphActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton jButtonAppleAssM;
    private javax.swing.JButton jButtonAppleAssP;
    private javax.swing.JButton jButtonAppleCpuM;
    private javax.swing.JButton jButtonAppleCpuP;
    private javax.swing.JButton jButtonAppleGpuM;
    private javax.swing.JButton jButtonAppleGpuP;
    private javax.swing.JButton jButtonApplePlacaM;
    private javax.swing.JButton jButtonApplePlacaP;
    private javax.swing.JButton jButtonApplePlacaP1;
    private javax.swing.JButton jButtonApplePsuM;
    private javax.swing.JButton jButtonApplePsuP;
    private javax.swing.JButton jButtonAppleRamM;
    private javax.swing.JButton jButtonAppleRamP;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonDellAssM1;
    private javax.swing.JButton jButtonDellAssP1;
    private javax.swing.JButton jButtonDellCpuM1;
    private javax.swing.JButton jButtonDellCpuP1;
    private javax.swing.JButton jButtonDellGpuM1;
    private javax.swing.JButton jButtonDellGpuP1;
    private javax.swing.JButton jButtonDellPlacaM1;
    private javax.swing.JButton jButtonDellPsuM1;
    private javax.swing.JButton jButtonDellPsuP1;
    private javax.swing.JButton jButtonDellRamM1;
    private javax.swing.JButton jButtonDellRamP1;
    private javax.swing.JButton jButtonGoToSTORAGE;
    private javax.swing.JButton jButtonHPAssM2;
    private javax.swing.JButton jButtonHPAssP2;
    private javax.swing.JButton jButtonHPCpuM2;
    private javax.swing.JButton jButtonHPCpuP2;
    private javax.swing.JButton jButtonHPGpuM2;
    private javax.swing.JButton jButtonHPGpuP2;
    private javax.swing.JButton jButtonHPPlacaM2;
    private javax.swing.JButton jButtonHPPlacaP2;
    private javax.swing.JButton jButtonHPPsuM2;
    private javax.swing.JButton jButtonHPPsuP2;
    private javax.swing.JButton jButtonHPRamM2;
    private javax.swing.JButton jButtonHPRamP2;
    private javax.swing.JButton jButtonShowGraph;
    private javax.swing.JButton jButtonStartSim;
    private javax.swing.JButton jButtonStopSim;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22APPLE;
    private javax.swing.JLabel jLabel23APPLE;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26DELL;
    private javax.swing.JLabel jLabel27DELL;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43HP;
    private javax.swing.JLabel jLabel44HP;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAppleAssCant;
    private javax.swing.JLabel jLabelAppleCost;
    private javax.swing.JLabel jLabelAppleCpuCant;
    private javax.swing.JLabel jLabelAppleDirStatus;
    private javax.swing.JLabel jLabelAppleGanancia;
    private javax.swing.JLabel jLabelAppleGpuCant;
    private javax.swing.JLabel jLabelApplePc;
    private javax.swing.JLabel jLabelApplePcGpu;
    private javax.swing.JLabel jLabelApplePlacasCant;
    private javax.swing.JLabel jLabelApplePmStatus;
    private javax.swing.JLabel jLabelApplePsuCant;
    private javax.swing.JLabel jLabelAppleRamCant;
    private javax.swing.JLabel jLabelAppleUtility;
    private javax.swing.JLabel jLabelDaysToDeliver;
    private javax.swing.JLabel jLabelDellAssCant1;
    private javax.swing.JLabel jLabelDellCost1;
    private javax.swing.JLabel jLabelDellCpuCant1;
    private javax.swing.JLabel jLabelDellDirStatus1;
    private javax.swing.JLabel jLabelDellGanancia1;
    private javax.swing.JLabel jLabelDellGpuCant1;
    private javax.swing.JLabel jLabelDellPc1;
    private javax.swing.JLabel jLabelDellPcGpu1;
    private javax.swing.JLabel jLabelDellPlacasCant1;
    private javax.swing.JLabel jLabelDellPmStatus1;
    private javax.swing.JLabel jLabelDellPsuCant1;
    private javax.swing.JLabel jLabelDellRamCant1;
    private javax.swing.JLabel jLabelDellUtility1;
    private javax.swing.JLabel jLabelHPAssCant2;
    private javax.swing.JLabel jLabelHPCost2;
    private javax.swing.JLabel jLabelHPCpuCant2;
    private javax.swing.JLabel jLabelHPDirStatus2;
    private javax.swing.JLabel jLabelHPGanancia2;
    private javax.swing.JLabel jLabelHPGpuCant2;
    private javax.swing.JLabel jLabelHPPc2;
    private javax.swing.JLabel jLabelHPPcGpu2;
    private javax.swing.JLabel jLabelHPPlacasCant2;
    private javax.swing.JLabel jLabelHPPmStatus2;
    private javax.swing.JLabel jLabelHPPsuCant2;
    private javax.swing.JLabel jLabelHPRamCant2;
    private javax.swing.JLabel jLabelHPUtility2;
    private javax.swing.JLabel jLabelSimDaysPassed;
    // End of variables declaration//GEN-END:variables
}
