/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import proyecto1so.Company;
import proyecto1so.SimulationController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import proyecto1so.UtilityGraph;
/**
 *
 * @author berna
 */
public class StorageGUI extends javax.swing.JFrame {

    private final Company apple;
    private final Company hp;
    private final Company dell;
    private int[] workerTimes = {4000, 4000, 1000, 200, 2000 };
    private final SimulationController controller;
    /**
     * Creates new form DashboardMenu
     */
    public StorageGUI(SimulationController controller, Company apple, Company hp, Company dell) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = controller;
        this.apple = apple;
        this.hp = hp;
        this.dell = dell;
        
        jLabelApplePlacasCant.setText(Integer.toString(apple.getStorage().getMAX_MOTHERBOARDS()));
        jLabelAppleCpuCant.setText(Integer.toString(apple.getStorage().getMAX_CPUS()));
        jLabelAppleRamCant.setText(Integer.toString(apple.getStorage().getMAX_RAMS()));
        jLabelApplePsuCant.setText(Integer.toString(apple.getStorage().getMAX_POWER_SUPPLIES()));
        jLabelAppleGpuCant.setText(Integer.toString(apple.getStorage().getMAX_MOTHERBOARDS()));
        jLabelDellPlacasCant1.setText(Integer.toString(hp.getStorage().getMAX_MOTHERBOARDS()));
        jLabelDellCpuCant1.setText(Integer.toString(hp.getStorage().getMAX_CPUS()));
        jLabelDellRamCant1.setText(Integer.toString(hp.getStorage().getMAX_RAMS()));
        jLabelDellPsuCant1.setText(Integer.toString(hp.getStorage().getMAX_POWER_SUPPLIES()));
        jLabelDellGpuCant1.setText(Integer.toString(hp.getStorage().getMAX_GRAPHIC_CARDS()));   
        jLabelHPPlacasCant2.setText(Integer.toString(dell.getStorage().getMAX_MOTHERBOARDS()));
        jLabelHPCpuCant2.setText(Integer.toString(dell.getStorage().getMAX_CPUS()));
        jLabelHPRamCant2.setText(Integer.toString(dell.getStorage().getMAX_RAMS()));
        jLabelHPPsuCant2.setText(Integer.toString(dell.getStorage().getMAX_POWER_SUPPLIES()));
        jLabelHPGpuCant2.setText(Integer.toString(dell.getStorage().getMAX_GRAPHIC_CARDS()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApplePlacaM = new javax.swing.JButton();
        jButtonApplePlacaP = new javax.swing.JButton();
        jLabelApplePlacasCant = new javax.swing.JLabel();
        jButtonAppleCpuM = new javax.swing.JButton();
        jLabelAppleCpuCant = new javax.swing.JLabel();
        jButtonAppleCpuP = new javax.swing.JButton();
        jButtonAppleRamM = new javax.swing.JButton();
        jLabelAppleRamCant = new javax.swing.JLabel();
        jButtonAppleRamP = new javax.swing.JButton();
        jButtonApplePsuM = new javax.swing.JButton();
        jLabelApplePsuCant = new javax.swing.JLabel();
        jButtonApplePsuP = new javax.swing.JButton();
        jButtonAppleGpuM = new javax.swing.JButton();
        jLabelAppleGpuCant = new javax.swing.JLabel();
        jButtonAppleGpuP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonStartSim = new javax.swing.JButton();
        jButtonDellPlacaM1 = new javax.swing.JButton();
        jButtonApplePlacaP1 = new javax.swing.JButton();
        jLabelDellPlacasCant1 = new javax.swing.JLabel();
        jButtonDellCpuM1 = new javax.swing.JButton();
        jLabelDellCpuCant1 = new javax.swing.JLabel();
        jButtonDellCpuP1 = new javax.swing.JButton();
        jButtonDellRamM1 = new javax.swing.JButton();
        jLabelDellRamCant1 = new javax.swing.JLabel();
        jButtonDellRamP1 = new javax.swing.JButton();
        jButtonDellPsuM1 = new javax.swing.JButton();
        jLabelDellPsuCant1 = new javax.swing.JLabel();
        jButtonDellPsuP1 = new javax.swing.JButton();
        jButtonDellGpuM1 = new javax.swing.JButton();
        jLabelDellGpuCant1 = new javax.swing.JLabel();
        jButtonDellGpuP1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButtonHPPlacaM2 = new javax.swing.JButton();
        jButtonHPPlacaP2 = new javax.swing.JButton();
        jLabelHPPlacasCant2 = new javax.swing.JLabel();
        jButtonHPCpuM2 = new javax.swing.JButton();
        jLabelHPCpuCant2 = new javax.swing.JLabel();
        jButtonHPCpuP2 = new javax.swing.JButton();
        jButtonHPRamM2 = new javax.swing.JButton();
        jLabelHPRamCant2 = new javax.swing.JLabel();
        jButtonHPRamP2 = new javax.swing.JButton();
        jButtonHPPsuM2 = new javax.swing.JButton();
        jLabelHPPsuCant2 = new javax.swing.JLabel();
        jButtonHPPsuP2 = new javax.swing.JButton();
        jButtonHPGpuM2 = new javax.swing.JButton();
        jLabelHPGpuCant2 = new javax.swing.JLabel();
        jButtonHPGpuP2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonApplePlacaM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePlacaM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePlacaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonApplePlacaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePlacaMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePlacaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 20, 20));

        jButtonApplePlacaP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePlacaP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePlacaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonApplePlacaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePlacaPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePlacaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 20, 20));

        jLabelApplePlacasCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePlacasCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePlacasCant.setText("x");
        getContentPane().add(jLabelApplePlacasCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jButtonAppleCpuM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleCpuM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleCpuM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleCpuM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleCpuMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleCpuM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 20, 20));

        jLabelAppleCpuCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleCpuCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleCpuCant.setText("x");
        getContentPane().add(jLabelAppleCpuCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jButtonAppleCpuP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleCpuP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleCpuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleCpuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleCpuPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleCpuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 20, 20));

        jButtonAppleRamM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleRamM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleRamM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleRamM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleRamMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleRamM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 20, 20));

        jLabelAppleRamCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleRamCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleRamCant.setText("x");
        getContentPane().add(jLabelAppleRamCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jButtonAppleRamP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleRamP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleRamP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleRamP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleRamPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleRamP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 20, 20));

        jButtonApplePsuM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePsuM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePsuM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonApplePsuM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePsuMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePsuM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 20, 20));

        jLabelApplePsuCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelApplePsuCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApplePsuCant.setText("x");
        getContentPane().add(jLabelApplePsuCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jButtonApplePsuP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePsuP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePsuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonApplePsuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePsuPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePsuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 20, 20));

        jButtonAppleGpuM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleGpuM.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleGpuM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonAppleGpuM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleGpuMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleGpuM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 20, 20));

        jLabelAppleGpuCant.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelAppleGpuCant.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAppleGpuCant.setText("x");
        getContentPane().add(jLabelAppleGpuCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jButtonAppleGpuP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonAppleGpuP.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAppleGpuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonAppleGpuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppleGpuPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppleGpuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 20, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Placas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 37, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CPU");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 37, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("RAM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 37, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("GPU");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 37, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PSU");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 37, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cant por Almacen:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VS.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, 80));

        jButtonStartSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HOME.png"))); // NOI18N
        jButtonStartSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartSimActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStartSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 80, 40));

        jButtonDellPlacaM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellPlacaM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellPlacaM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellPlacaM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellPlacaM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellPlacaM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 20, 20));

        jButtonApplePlacaP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonApplePlacaP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonApplePlacaP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonApplePlacaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplePlacaP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApplePlacaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 20, 20));

        jLabelDellPlacasCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPlacasCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPlacasCant1.setText("x");
        getContentPane().add(jLabelDellPlacasCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButtonDellCpuM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellCpuM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellCpuM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellCpuM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellCpuM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellCpuM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 20, 20));

        jLabelDellCpuCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellCpuCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellCpuCant1.setText("x");
        getContentPane().add(jLabelDellCpuCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jButtonDellCpuP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellCpuP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellCpuP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellCpuP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellCpuP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellCpuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 20, 20));

        jButtonDellRamM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellRamM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellRamM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellRamM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellRamM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellRamM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 20, 20));

        jLabelDellRamCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellRamCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellRamCant1.setText("x");
        getContentPane().add(jLabelDellRamCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jButtonDellRamP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellRamP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellRamP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellRamP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellRamP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellRamP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 20, 20));

        jButtonDellPsuM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellPsuM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellPsuM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellPsuM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellPsuM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellPsuM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 20, 20));

        jLabelDellPsuCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellPsuCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellPsuCant1.setText("x");
        getContentPane().add(jLabelDellPsuCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        jButtonDellPsuP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellPsuP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellPsuP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellPsuP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellPsuP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellPsuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 20, 20));

        jButtonDellGpuM1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellGpuM1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellGpuM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonDellGpuM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellGpuM1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellGpuM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 20, 20));

        jLabelDellGpuCant1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDellGpuCant1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDellGpuCant1.setText("x");
        getContentPane().add(jLabelDellGpuCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jButtonDellGpuP1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonDellGpuP1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDellGpuP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonDellGpuP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDellGpuP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDellGpuP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 20, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Placas");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 37, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("CPU");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 37, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("RAM");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 37, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("GPU");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 37, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cant por Almacen:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("PSU");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 37, -1));

        jButtonHPPlacaM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPlacaM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPlacaM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPPlacaM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPlacaM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPlacaM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 20, 20));

        jButtonHPPlacaP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPlacaP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPlacaP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPPlacaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPlacaP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPlacaP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 20, 20));

        jLabelHPPlacasCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPlacasCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPlacasCant2.setText("x");
        getContentPane().add(jLabelHPPlacasCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jButtonHPCpuM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPCpuM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPCpuM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPCpuM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPCpuM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPCpuM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 20, 20));

        jLabelHPCpuCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPCpuCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPCpuCant2.setText("x");
        getContentPane().add(jLabelHPCpuCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        jButtonHPCpuP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPCpuP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPCpuP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPCpuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPCpuP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPCpuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 20, 20));

        jButtonHPRamM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPRamM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPRamM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPRamM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPRamM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPRamM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 20, 20));

        jLabelHPRamCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPRamCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPRamCant2.setText("x");
        getContentPane().add(jLabelHPRamCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        jButtonHPRamP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPRamP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPRamP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPRamP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPRamP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPRamP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 20, 20));

        jButtonHPPsuM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPsuM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPsuM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPPsuM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPsuM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPsuM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 20, 20));

        jLabelHPPsuCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPPsuCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPPsuCant2.setText("x");
        getContentPane().add(jLabelHPPsuCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jButtonHPPsuP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPPsuP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPPsuP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPPsuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPPsuP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPPsuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 20, 20));

        jButtonHPGpuM2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPGpuM2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPGpuM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MENOS.png"))); // NOI18N
        jButtonHPGpuM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPGpuM2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPGpuM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 20, 20));

        jLabelHPGpuCant2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelHPGpuCant2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHPGpuCant2.setText("x");
        getContentPane().add(jLabelHPGpuCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        jButtonHPGpuP2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonHPGpuP2.setForeground(new java.awt.Color(0, 0, 0));
        jButtonHPGpuP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MAS.png"))); // NOI18N
        jButtonHPGpuP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPGpuP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHPGpuP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 20, 20));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Placas");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 37, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("CPU");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 37, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("RAM");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 37, -1));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("GPU");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 37, -1));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Cant por Almacen:");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("PSU");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 37, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FONDO.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 753, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApplePlacaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePlacaMActionPerformed
        apple.getStorage().setMAX_MOTHERBOARDS(apple.getStorage().getMAX_MOTHERBOARDS() - 1);
        jLabelApplePlacasCant.setText(Integer.toString(apple.getStorage().getMAX_MOTHERBOARDS()));

    }//GEN-LAST:event_jButtonApplePlacaMActionPerformed

    private void jButtonApplePlacaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePlacaPActionPerformed

        apple.getStorage().setMAX_MOTHERBOARDS(apple.getStorage().getMAX_MOTHERBOARDS() + 1);
        jLabelApplePlacasCant.setText(Integer.toString(apple.getStorage().getMAX_MOTHERBOARDS()));

    }//GEN-LAST:event_jButtonApplePlacaPActionPerformed

    private void jButtonAppleCpuMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleCpuMActionPerformed
        apple.getStorage().setMAX_CPUS(apple.getStorage().getMAX_CPUS() - 1);
        jLabelAppleCpuCant.setText(Integer.toString(apple.getStorage().getMAX_CPUS()));
    }//GEN-LAST:event_jButtonAppleCpuMActionPerformed

    private void jButtonAppleCpuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleCpuPActionPerformed
        apple.getStorage().setMAX_CPUS(apple.getStorage().getMAX_CPUS() + 1);
        jLabelAppleCpuCant.setText(Integer.toString(apple.getStorage().getMAX_CPUS()));
    }//GEN-LAST:event_jButtonAppleCpuPActionPerformed

    private void jButtonAppleRamMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleRamMActionPerformed
        apple.getStorage().setMAX_RAMS(apple.getStorage().getMAX_RAMS() - 1);
        jLabelAppleRamCant.setText(Integer.toString(apple.getStorage().getMAX_RAMS()));
    }//GEN-LAST:event_jButtonAppleRamMActionPerformed

    private void jButtonAppleRamPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleRamPActionPerformed
        apple.getStorage().setMAX_RAMS(apple.getStorage().getMAX_RAMS() + 1);
        jLabelAppleRamCant.setText(Integer.toString(apple.getStorage().getMAX_RAMS()));
    }//GEN-LAST:event_jButtonAppleRamPActionPerformed

    private void jButtonApplePsuMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePsuMActionPerformed
        apple.getStorage().setMAX_POWER_SUPPLIES(apple.getStorage().getMAX_POWER_SUPPLIES() - 1);
        jLabelApplePsuCant.setText(Integer.toString(apple.getStorage().getMAX_POWER_SUPPLIES()));
    }//GEN-LAST:event_jButtonApplePsuMActionPerformed

    private void jButtonApplePsuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePsuPActionPerformed
        apple.getStorage().setMAX_POWER_SUPPLIES(apple.getStorage().getMAX_POWER_SUPPLIES() + 1);
        jLabelApplePsuCant.setText(Integer.toString(apple.getStorage().getMAX_POWER_SUPPLIES()));
    }//GEN-LAST:event_jButtonApplePsuPActionPerformed

    private void jButtonAppleGpuMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleGpuMActionPerformed
        apple.getStorage().setMAX_GRAPHIC_CARDS(apple.getStorage().getMAX_GRAPHIC_CARDS() - 1);
        jLabelAppleGpuCant.setText(Integer.toString(apple.getStorage().getMAX_GRAPHIC_CARDS()));
    }//GEN-LAST:event_jButtonAppleGpuMActionPerformed

    private void jButtonAppleGpuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppleGpuPActionPerformed
        apple.getStorage().setMAX_MOTHERBOARDS(apple.getStorage().getMAX_MOTHERBOARDS() + 1);
        jLabelAppleGpuCant.setText(Integer.toString(apple.getStorage().getMAX_MOTHERBOARDS()));
    }//GEN-LAST:event_jButtonAppleGpuPActionPerformed

    private void jButtonStartSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartSimActionPerformed
        DashboardMenu a = new DashboardMenu(controller, apple, hp, dell);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonStartSimActionPerformed

    private void jButtonDellPlacaM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellPlacaM1ActionPerformed
        hp.getStorage().setMAX_MOTHERBOARDS(hp.getStorage().getMAX_MOTHERBOARDS() - 1);
        jLabelDellPlacasCant1.setText(Integer.toString(hp.getStorage().getMAX_MOTHERBOARDS()));
    }//GEN-LAST:event_jButtonDellPlacaM1ActionPerformed

    private void jButtonApplePlacaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplePlacaP1ActionPerformed
        hp.getStorage().setMAX_MOTHERBOARDS(hp.getStorage().getMAX_MOTHERBOARDS() + 1);
        jLabelDellPlacasCant1.setText(Integer.toString(hp.getStorage().getMAX_MOTHERBOARDS()));
    }//GEN-LAST:event_jButtonApplePlacaP1ActionPerformed

    private void jButtonDellCpuM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellCpuM1ActionPerformed
        hp.getStorage().setMAX_CPUS(hp.getStorage().getMAX_CPUS() - 1);
        jLabelDellCpuCant1.setText(Integer.toString(hp.getStorage().getMAX_CPUS()));
    }//GEN-LAST:event_jButtonDellCpuM1ActionPerformed

    private void jButtonDellCpuP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellCpuP1ActionPerformed
        hp.getStorage().setMAX_CPUS(hp.getStorage().getMAX_CPUS() + 1);
        jLabelDellCpuCant1.setText(Integer.toString(hp.getStorage().getMAX_CPUS()));
    }//GEN-LAST:event_jButtonDellCpuP1ActionPerformed

    private void jButtonDellRamM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellRamM1ActionPerformed
        hp.getStorage().setMAX_RAMS(hp.getStorage().getMAX_RAMS() - 1);
        jLabelDellRamCant1.setText(Integer.toString(hp.getStorage().getMAX_RAMS()));
    }//GEN-LAST:event_jButtonDellRamM1ActionPerformed

    private void jButtonDellRamP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellRamP1ActionPerformed
        hp.getStorage().setMAX_RAMS(hp.getStorage().getMAX_RAMS() + 1);
        jLabelDellRamCant1.setText(Integer.toString(hp.getStorage().getMAX_RAMS()));
    }//GEN-LAST:event_jButtonDellRamP1ActionPerformed

    private void jButtonDellPsuM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellPsuM1ActionPerformed
        hp.getStorage().setMAX_POWER_SUPPLIES(hp.getStorage().getMAX_POWER_SUPPLIES() - 1);
        jLabelDellPsuCant1.setText(Integer.toString(hp.getStorage().getMAX_POWER_SUPPLIES()));
    }//GEN-LAST:event_jButtonDellPsuM1ActionPerformed

    private void jButtonDellPsuP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellPsuP1ActionPerformed
        hp.getStorage().setMAX_POWER_SUPPLIES(hp.getStorage().getMAX_POWER_SUPPLIES() + 1);
        jLabelDellPsuCant1.setText(Integer.toString(hp.getStorage().getMAX_POWER_SUPPLIES()));
    }//GEN-LAST:event_jButtonDellPsuP1ActionPerformed

    private void jButtonDellGpuM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellGpuM1ActionPerformed
        hp.getStorage().setMAX_GRAPHIC_CARDS(hp.getStorage().getMAX_GRAPHIC_CARDS() - 1);
        jLabelDellGpuCant1.setText(Integer.toString(hp.getStorage().getMAX_GRAPHIC_CARDS()));
    }//GEN-LAST:event_jButtonDellGpuM1ActionPerformed

    private void jButtonDellGpuP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDellGpuP1ActionPerformed
        hp.getStorage().setMAX_GRAPHIC_CARDS(hp.getStorage().getMAX_GRAPHIC_CARDS() + 1);
        jLabelDellGpuCant1.setText(Integer.toString(hp.getStorage().getMAX_GRAPHIC_CARDS()));
    }//GEN-LAST:event_jButtonDellGpuP1ActionPerformed

    private void jButtonHPPlacaM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPlacaM2ActionPerformed
        dell.getStorage().setMAX_MOTHERBOARDS(dell.getStorage().getMAX_MOTHERBOARDS() - 1);
        jLabelHPPlacasCant2.setText(Integer.toString(dell.getStorage().getMAX_MOTHERBOARDS()));
    }//GEN-LAST:event_jButtonHPPlacaM2ActionPerformed

    private void jButtonHPPlacaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPlacaP2ActionPerformed
        dell.getStorage().setMAX_MOTHERBOARDS(dell.getStorage().getMAX_MOTHERBOARDS() + 1);
        jLabelHPPlacasCant2.setText(Integer.toString(dell.getStorage().getMAX_MOTHERBOARDS()));
    }//GEN-LAST:event_jButtonHPPlacaP2ActionPerformed

    private void jButtonHPCpuM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPCpuM2ActionPerformed
        dell.getStorage().setMAX_CPUS(dell.getStorage().getMAX_CPUS() - 1);
        jLabelHPCpuCant2.setText(Integer.toString(dell.getStorage().getMAX_CPUS()));
    }//GEN-LAST:event_jButtonHPCpuM2ActionPerformed

    private void jButtonHPCpuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPCpuP2ActionPerformed
        dell.getStorage().setMAX_CPUS(dell.getStorage().getMAX_CPUS() + 1);
        jLabelHPCpuCant2.setText(Integer.toString(dell.getStorage().getMAX_CPUS()));
    }//GEN-LAST:event_jButtonHPCpuP2ActionPerformed

    private void jButtonHPRamM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPRamM2ActionPerformed
        dell.getStorage().setMAX_RAMS(dell.getStorage().getMAX_RAMS() - 1);
        jLabelHPRamCant2.setText(Integer.toString(dell.getStorage().getMAX_RAMS()));
    }//GEN-LAST:event_jButtonHPRamM2ActionPerformed

    private void jButtonHPRamP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPRamP2ActionPerformed
        dell.getStorage().setMAX_RAMS(dell.getStorage().getMAX_RAMS() + 1);
        jLabelHPRamCant2.setText(Integer.toString(dell.getStorage().getMAX_RAMS()));
    }//GEN-LAST:event_jButtonHPRamP2ActionPerformed

    private void jButtonHPPsuM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPsuM2ActionPerformed
        dell.getStorage().setMAX_POWER_SUPPLIES(dell.getStorage().getMAX_POWER_SUPPLIES() - 1);
        jLabelHPPsuCant2.setText(Integer.toString(dell.getStorage().getMAX_POWER_SUPPLIES()));
    }//GEN-LAST:event_jButtonHPPsuM2ActionPerformed

    private void jButtonHPPsuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPPsuP2ActionPerformed
        dell.getStorage().setMAX_POWER_SUPPLIES(dell.getStorage().getMAX_POWER_SUPPLIES() + 1);
        jLabelHPPsuCant2.setText(Integer.toString(dell.getStorage().getMAX_POWER_SUPPLIES()));
    }//GEN-LAST:event_jButtonHPPsuP2ActionPerformed

    private void jButtonHPGpuM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPGpuM2ActionPerformed
        dell.getStorage().setMAX_GRAPHIC_CARDS(dell.getStorage().getMAX_GRAPHIC_CARDS() - 1);
        jLabelHPGpuCant2.setText(Integer.toString(dell.getStorage().getMAX_GRAPHIC_CARDS()));
    }//GEN-LAST:event_jButtonHPGpuM2ActionPerformed

    private void jButtonHPGpuP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPGpuP2ActionPerformed
        dell.getStorage().setMAX_GRAPHIC_CARDS(dell.getStorage().getMAX_GRAPHIC_CARDS() + 1);
        jLabelHPGpuCant2.setText(Integer.toString(dell.getStorage().getMAX_GRAPHIC_CARDS()));
    }//GEN-LAST:event_jButtonHPGpuP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton jButtonAppleCpuM;
    private javax.swing.JButton jButtonAppleCpuP;
    private javax.swing.JButton jButtonAppleGpuM;
    private javax.swing.JButton jButtonAppleGpuP;
    private javax.swing.JButton jButtonApplePlacaM;
    private javax.swing.JButton jButtonApplePlacaP;
    private javax.swing.JButton jButtonApplePlacaP1;
    private javax.swing.JButton jButtonApplePsuM;
    private javax.swing.JButton jButtonApplePsuP;
    private javax.swing.JButton jButtonAppleRamM;
    private javax.swing.JButton jButtonAppleRamP;
    private javax.swing.JButton jButtonDellCpuM1;
    private javax.swing.JButton jButtonDellCpuP1;
    private javax.swing.JButton jButtonDellGpuM1;
    private javax.swing.JButton jButtonDellGpuP1;
    private javax.swing.JButton jButtonDellPlacaM1;
    private javax.swing.JButton jButtonDellPsuM1;
    private javax.swing.JButton jButtonDellPsuP1;
    private javax.swing.JButton jButtonDellRamM1;
    private javax.swing.JButton jButtonDellRamP1;
    private javax.swing.JButton jButtonHPCpuM2;
    private javax.swing.JButton jButtonHPCpuP2;
    private javax.swing.JButton jButtonHPGpuM2;
    private javax.swing.JButton jButtonHPGpuP2;
    private javax.swing.JButton jButtonHPPlacaM2;
    private javax.swing.JButton jButtonHPPlacaP2;
    private javax.swing.JButton jButtonHPPsuM2;
    private javax.swing.JButton jButtonHPPsuP2;
    private javax.swing.JButton jButtonHPRamM2;
    private javax.swing.JButton jButtonHPRamP2;
    private javax.swing.JButton jButtonStartSim;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAppleCpuCant;
    private javax.swing.JLabel jLabelAppleGpuCant;
    private javax.swing.JLabel jLabelApplePlacasCant;
    private javax.swing.JLabel jLabelApplePsuCant;
    private javax.swing.JLabel jLabelAppleRamCant;
    private javax.swing.JLabel jLabelDellCpuCant1;
    private javax.swing.JLabel jLabelDellGpuCant1;
    private javax.swing.JLabel jLabelDellPlacasCant1;
    private javax.swing.JLabel jLabelDellPsuCant1;
    private javax.swing.JLabel jLabelDellRamCant1;
    private javax.swing.JLabel jLabelHPCpuCant2;
    private javax.swing.JLabel jLabelHPGpuCant2;
    private javax.swing.JLabel jLabelHPPlacasCant2;
    private javax.swing.JLabel jLabelHPPsuCant2;
    private javax.swing.JLabel jLabelHPRamCant2;
    // End of variables declaration//GEN-END:variables
}
